/**
 * test/unit/verify-port.test.ts — unit tests for the detectTestCommand detector
 * in src/infra/verify-port.ts.
 *
 * Each test creates a minimal temp directory containing only the marker files
 * needed by one detector, calls nodeVerifyPort.detectTestCommand(), and asserts
 * the returned DetectedTestCommand (or null for placeholder scripts).
 *
 * Run with:
 *   node --import ./test/register.mjs --test "test/unit/verify-port.test.ts"
 *
 * Zero live execs — only the detection (fs-read) path is exercised.
 */

import { afterEach, beforeEach, describe, it } from 'vitest';
import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';

import { nodeVerifyPort } from '../../src/infra/verify-port.ts';

// ---------------------------------------------------------------------------
// Temp-dir fixture helpers
// ---------------------------------------------------------------------------

let dir: string;

beforeEach(async () => {
  dir = await mkdtemp(join(tmpdir(), `vport-test-${randomUUID()}-`));
});

afterEach(async () => {
  await rm(dir, { recursive: true, force: true });
});

async function write(rel: string, content: string): Promise<void> {
  await writeFile(join(dir, rel), content, 'utf8');
}

async function makeDir(rel: string): Promise<void> {
  await mkdir(join(dir, rel), { recursive: true });
}

// ---------------------------------------------------------------------------
// Existing detectors — must still resolve identically (priority preserved)
// ---------------------------------------------------------------------------

describe('detectTestCommand — npm (existing, must not regress)', () => {
  it('package.json with real test script → npm test', async () => {
    await write('package.json', JSON.stringify({ scripts: { test: 'node --test' } }));
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'npm test', command: 'npm', args: ['test', '--silent'] });
  });

  it('placeholder script (no test specified) → null', async () => {
    await write(
      'package.json',
      JSON.stringify({ scripts: { test: 'echo "Error: no test specified" && exit 1' } }),
    );
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });

  it('no test script key at all → null', async () => {
    await write('package.json', JSON.stringify({ scripts: {} }));
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });
});

describe('detectTestCommand — pytest (existing)', () => {
  it('pyproject.toml → pytest', async () => {
    await write('pyproject.toml', '[tool.pytest.ini_options]\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'pytest', command: 'pytest', args: ['-q'] });
  });

  it('pytest.ini → pytest', async () => {
    await write('pytest.ini', '[pytest]\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'pytest', command: 'pytest', args: ['-q'] });
  });
});

describe('detectTestCommand — cargo (existing)', () => {
  it('Cargo.toml → cargo test', async () => {
    await write('Cargo.toml', '[package]\nname = "foo"\nversion = "0.1.0"\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'cargo test', command: 'cargo', args: ['test'] });
  });
});

describe('detectTestCommand — go (existing)', () => {
  it('go.mod → go test', async () => {
    await write('go.mod', 'module example.com/foo\n\ngo 1.21\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'go test', command: 'go', args: ['test', './...'] });
  });
});

// ---------------------------------------------------------------------------
// pnpm / yarn — lockfile overrides npm when package.json has a real test script
// ---------------------------------------------------------------------------

describe('detectTestCommand — pnpm / yarn (new lockfile detection)', () => {
  it('pnpm-lock.yaml present + real test script → pnpm test', async () => {
    await write('package.json', JSON.stringify({ scripts: { test: 'vitest run' } }));
    await write('pnpm-lock.yaml', 'lockfileVersion: 9\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'pnpm test', command: 'pnpm', args: ['test'] });
  });

  it('yarn.lock present + real test script → yarn test', async () => {
    await write('package.json', JSON.stringify({ scripts: { test: 'jest' } }));
    await write('yarn.lock', '# THIS IS AN AUTOGENERATED FILE.\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'yarn test', command: 'yarn', args: ['test'] });
  });

  it('yarn.lock present but placeholder test script → null (isRealTestScript gate)', async () => {
    await write(
      'package.json',
      JSON.stringify({ scripts: { test: 'echo "Error: no test specified" && exit 1' } }),
    );
    await write('yarn.lock', '# THIS IS AN AUTOGENERATED FILE.\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });
});

// ---------------------------------------------------------------------------
// Elixir / mix
// ---------------------------------------------------------------------------

describe('detectTestCommand — Elixir / mix (new)', () => {
  it('mix.exs present → mix test', async () => {
    await write('mix.exs', 'defmodule MyApp.MixProject do\n  use Mix.Project\nend\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'mix test', command: 'mix', args: ['test'] });
  });

  it('no mix.exs → does not detect mix', async () => {
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });
});

// ---------------------------------------------------------------------------
// .NET / dotnet
// ---------------------------------------------------------------------------

describe('detectTestCommand — dotnet (new)', () => {
  it('*.csproj present → dotnet test', async () => {
    await write('MyApp.csproj', '<Project Sdk="Microsoft.NET.Sdk"></Project>\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'dotnet test', command: 'dotnet', args: ['test'] });
  });

  it('*.sln present → dotnet test', async () => {
    await write('MyApp.sln', 'Microsoft Visual Studio Solution File\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'dotnet test', command: 'dotnet', args: ['test'] });
  });
});

// ---------------------------------------------------------------------------
// Gradle
// ---------------------------------------------------------------------------

describe('detectTestCommand — Gradle (new)', () => {
  it('gradlew present → ./gradlew test', async () => {
    await write('gradlew', '#!/bin/sh\nexec gradle "$@"\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'gradle test', command: './gradlew', args: ['test'] });
  });

  it('build.gradle (no gradlew) → gradle test', async () => {
    await write('build.gradle', 'apply plugin: "java"\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'gradle test', command: 'gradle', args: ['test'] });
  });

  it('build.gradle.kts (no gradlew) → gradle test', async () => {
    await write('build.gradle.kts', 'plugins { kotlin("jvm") }\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'gradle test', command: 'gradle', args: ['test'] });
  });
});

// ---------------------------------------------------------------------------
// Ruby / rake / rspec
// ---------------------------------------------------------------------------

describe('detectTestCommand — Ruby / rake (new)', () => {
  it('Rakefile with task :test → rake test', async () => {
    await write('Rakefile', 'require "rake/testtask"\ntask :test do\n  ruby "test/**/*_test.rb"\nend\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'rake test', command: 'rake', args: ['test'] });
  });

  it('Rakefile with task "test" (double-quote style) → rake test', async () => {
    await write('Rakefile', 'task "test" do\n  sh "ruby test/all.rb"\nend\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'rake test', command: 'rake', args: ['test'] });
  });

  it('Rakefile WITHOUT a test task → does not detect rake', async () => {
    await write('Rakefile', 'task :build do\n  sh "make build"\nend\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });
});

describe('detectTestCommand — rspec (new)', () => {
  it('.rspec present → rspec', async () => {
    await write('.rspec', '--color\n--format documentation\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'rspec', command: 'rspec', args: [] });
  });

  it('spec/ directory present → rspec', async () => {
    await makeDir('spec');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'rspec', command: 'rspec', args: [] });
  });
});

// ---------------------------------------------------------------------------
// PHP / composer
// ---------------------------------------------------------------------------

describe('detectTestCommand — PHP / composer (new)', () => {
  it('composer.json with real test script → composer test', async () => {
    await write(
      'composer.json',
      JSON.stringify({ scripts: { test: './vendor/bin/phpunit' } }),
    );
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'composer test', command: 'composer', args: ['test'] });
  });

  it('composer.json WITHOUT a test script → null', async () => {
    await write('composer.json', JSON.stringify({ require: { php: '>=8.1' } }));
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });

  it('malformed composer.json → null (fail-soft)', async () => {
    await write('composer.json', '{ invalid json ');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });
});

// ---------------------------------------------------------------------------
// Make / just
// ---------------------------------------------------------------------------

describe('detectTestCommand — just (new)', () => {
  it('justfile with test target → just test', async () => {
    await write(
      'justfile',
      '# run the test suite\ntest:\n    cargo test\n',
    );
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'just test', command: 'just', args: ['test'] });
  });

  it('Justfile (capital J) with test target → just test', async () => {
    await write(
      'Justfile',
      'test:\n    go test ./...\n',
    );
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'just test', command: 'just', args: ['test'] });
  });

  it('justfile WITHOUT a test target → does not detect just', async () => {
    await write('justfile', 'build:\n    cargo build\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });
});

describe('detectTestCommand — make (new)', () => {
  it('Makefile with test: target → make test', async () => {
    await write(
      'Makefile',
      '.PHONY: test\ntest:\n\tgo test ./...\n',
    );
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'make test', command: 'make', args: ['test'] });
  });

  it('GNUmakefile with test target → make test', async () => {
    await write(
      'GNUmakefile',
      'test:\n\t./run-tests.sh\n',
    );
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.deepEqual(cmd, { label: 'make test', command: 'make', args: ['test'] });
  });

  it('Makefile WITHOUT a test target → does not detect make', async () => {
    await write('Makefile', 'all:\n\techo done\n');
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });
});

// ---------------------------------------------------------------------------
// Empty directory → null (never fabricates)
// ---------------------------------------------------------------------------

describe('detectTestCommand — empty directory → null', () => {
  it('completely empty dir returns null', async () => {
    const cmd = await nodeVerifyPort.detectTestCommand(dir);
    assert.equal(cmd, null);
  });
});
